# Generated by Django 5.0.13 on 2025-04-07 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_rename_company_url_company_domain_and_more'),
        ('story', '0004_alter_story_article_url_alter_story_tagged_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_stories', to='story.story'),
        ),
        migrations.AlterField(
            model_name='story',
            name='tagged_companies',
            field=models.ManyToManyField(related_name='tagged_stories', to='company.company'),
        ),
    ]
