# Generated by Django 5.0.13 on 2025-04-07 12:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_story_root_alter_story_tagged_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='locations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='List of recognized location entities', null=True, size=None),
        ),
        migrations.AddField(
            model_name='story',
            name='organizations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='List of recognized organization entities', null=True, size=None),
        ),
        migrations.AddField(
            model_name='story',
            name='persons',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='List of recognized person entities', null=True, size=None),
        ),
    ]
